CREATE TABLE IF NOT EXISTS classes
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    study_year INT NOT NULL,
    mnemocode VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS students
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(32) NOT NULL,
    surname VARCHAR(32) NOT NULL,
    patronymic VARCHAR(32) NOT NULL,
    birth_year INT NOT NULL,
    gender VARCHAR(10) NOT NULL,
    class_id BIGINT,

    CONSTRAINT pk_students PRIMARY KEY (id),
    CONSTRAINT fk_students_to_classes FOREIGN KEY (class_id) REFERENCES classes (id)
        ON DELETE SET NULL ON UPDATE SET NULL
);

CREATE TABLE IF NOT EXISTS teachers
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    surname VARCHAR(32) NOT NULL,
    name VARCHAR(32) NOT NULL,
    patronymic VARCHAR(32) NOT NULL,
    birth_year INT NOT NULL,
    gender VARCHAR(10) NOT NULL,
    main_subject VARCHAR(32) NOT NULL,
    class_id BIGINT,

    CONSTRAINT pk_teachers PRIMARY KEY (id),
    CONSTRAINT fk_teachers_to_classes FOREIGN KEY (class_id) REFERENCES classes (id)
        ON DELETE SET NULL ON UPDATE SET NULL
);